### ISSUE TITLE
Can't use with NPM because there is no package.json

### ISSUE THREAD

**Issue by lastmjs** [earaujoassis/ubuntu-fontface#6]
I'm trying to move my project completely from bower to npm, and because this repo doesn't have a package.json with name and version fields, npm fails to install it. I would much rather not fork the project just to put a package.json in, so it would be nice to have that.

**Comment by achugaev93** [comment]
NPM has another purpose. It is a nodejs package manager. This means, that each package should contain only js code to use in nodejs apps. And this is not applicable for fonts and stylesheets.

**Comment by earaujoassis** [comment]
@achugaev93 There's also a discussion in #7 . Thank you for your contribution ;)

**Comment by earaujoassis** [comment]
#7 was also closed. Thank you, @lastmjs and @achugaev93 , for your contribution.

**Comment by earaujoassis** [comment]
#7 was reopened

**Comment by earaujoassis** [comment]
Closed by #7
